use case_study_1


-- 1. Display the number of states present in the LocationTable
	SELECT State, COUNT(*) AS state_count FROM dbo.Location GROUP BY State;
	SELECT COUNT(DISTINCT state) AS total_states FROM dbo.Location;

	select * from Product;

-- 2. How many products are of regular type?
	SELECT  COUNT(*) AS regular_product_count FROM dbo.PRODUCT WHERE Type = 'Regular';

	select * from fact

-- 3. How much spending has been done on marketing of product ID 1?

	SELECT SUM(Marketing) AS total_marketing_for_product_1 FROM fact WHERE productId = 1;

-- 4.What is the minimum sales of a product?
	select min(Sales) from fact;

-- 5. Display the max Cost of Good Sold (COGS).

	SELECT MAX(COGS) FROM fact;

-- 6. Display the details of the product where product type is coffee.

	Select * from product where product_type = 'coffee'
 
 -- 7. Display the details where total expenses are greater than 40.
	SELECT * FROM fact WHERE Total_expenses > 40;

-- 8. What is the average sales in area code 719?
	SELECT  AVG(Sales) AS average_sales FROM fact WHERE area_code=719;

-- 9. Find out the total profit generated by Colorado state
	Select sum(profit) as profit from fact F Join location l on f.area_code = l.area_code where l.state = 'Colorado';

-- 10. Display the average inventory for each product ID.
	SELECT productId, AVG(inventory) AS average_inventory
		FROM fact GROUP BY productId ORDER BY ProductId ASC;

-- 11. Display state in a sequential order in a Location Table.
	SELECT State, Area_code from Location ORDER BY State ASC;


-- 12. Display the average budget of the Product where the average budget margin should be greater than 100.
	SELECT productId, AVG(Budget_Margin) AS average_budget_margin
		FROM fact GROUP BY productId HAVING AVG(Budget_Margin) > 100;

-- 13. What is the total sales done on date 2010-01-01?

	SELECT SUM(Sales) AS total_sales FROM dbo.fact WHERE Date = '2010-01-01';

-- 14. Display the average total expense of each product ID on an individual date

	SELECT productId, Date, AVG(Total_expenses) AS average_total_expenses
		FROM fact GROUP BY productId, Date ORDER BY productId ASC;

-- 15. Display the table with the following attributes such as date, product ID, product_type, product, sales, profit, state, area_code.
	SELECT f.Date, f.productId, p.product_type, p.product, f.sales, f.profit, l.state, l.area_code
		FROM fact f 
			JOIN product p ON f.productId = p.productId
			JOIN Location l ON  f.area_code = l.area_code;